### PR TITLE
[feature]support group commit

### PR DESCRIPTION
**Pull request by vinlee19**
# Proposed changes

Issue Number: close #xxx

## Problem Summary:
suppport stream load with group commit mode
Describe the overview of changes.

## Checklist(Required)

1. Does it affect the original behavior: (Yes/No/I Don't know)
2. Has unit tests been added: (Yes/No/No Need)
3. Has document been added or modified: (Yes/No/No Need)
4. Does it need to update dependencies: (Yes/No)
5. Are there any changes that cannot be rolled back: (Yes/No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by gnehil — CHANGES_REQUESTED** [review]
It is necessary to check the configuration conflicts between group commit and two-phase commit and partial column update.

**Comment by vinlee19** [comment]
> It is necessary to check the configuration conflicts between group commit and two-phase commit and partial column update.

done

**Review by gnehil — APPROVED** [review]
LGTM

**Review by JNSimba — APPROVED** [review]
LGTM

**Pull request merged**
