### PR TITLE
[bug] fix stream dataframe writing to doris json parse exception

### LINKED ISSUE #47: [Bug] spark stream dataframe write to doris json parsing exeception
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

`spark stream write to doris` occurs the follwing exception:

```shell
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('-' (code 45)): Expected space separating root-level values
 at [Source: (String)"2022-08-23 12:09:22.706"; line: 1, column: 6]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1840)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:712)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:637)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportMissingRootWS(ParserMinimalBase.java:684)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._verifyRootSpace(ReaderBasedJsonParser.java:1678)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._parsePosNumber(ReaderBasedJsonParser.java:1321)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:769)
	at com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4231)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2711)
	at org.apache.doris.spark.sql.DorisStreamLoadSink.$anonfun$write$3(DorisStreamLoadSink.scala:58)
	at org.apache.doris.spark.sql.DorisStreamLoadSink.$anonfun$write$3$adapted(DorisStreamLoadSink.scala:56)
	at scala.collection.immutable.Range.foreach(Range.scala:156)
	at org.apache.doris.spark.sql.DorisStreamLoadSink.$anonfun$write$2(DorisStreamLoadSink.scala:56)
	at org.apache.doris.spark.sql.DorisStreamLoadSink.$anonfun$write$2$adapted(DorisStreamLoadSink.scala:54)
	at scala.collection.Iterator.foreach(Iterator.scala:944)
	at scala.collection.Iterator.foreach$(Iterator.scala:944)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.foreach(WholeStageCodegenExec.scala:753)
	at org.apache.doris.spark.sql.DorisStreamLoadSink.$anonfun$write$1(DorisStreamLoadSink.scala:54)
	at org.apache.doris.spark.sql.DorisStreamLoadSink.$anonfun$write$1$adapted(DorisStreamLoadSink.scala:51)
	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2(RDD.scala:1020)
	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2$adapted(RDD.scala:1020)
	at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2236)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

### What You Expected?

doris-spark-connector can write stream dataframe to doris

### How to Reproduce?

eg:
```scala
    df.selectExpr("CAST(timestamp AS STRING)", "CAST(partition as INT)")
      .writeStream
      .format("doris")
      .option("checkpointLocation", "/tmp/test")
      .option("doris.table.identifier", dorisTable)
      .option("doris.fenodes", dorisFeNodes)
      .option("user", dorisUser)
      .option("password", dorisPwd)
      .start().awaitTermination()
    spark.stop()
```

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by chovy-3012**
# Proposed changes

Issue Number: close #47 

## Problem Summary:

stream dataframe can write to doris

## Checklist(Required)

1. Does it affect the original behavior: (Yes/No/I Don't know)
No
3. Has unit tests been added: (Yes/No/No Need)
No Need
5. Has document been added or modified: (Yes/No/No Need)
No Need
7. Does it need to update dependencies: (Yes/No)
No
9. Are there any changes that cannot be rolled back: (Yes/No)
No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by caoliang-web** [comment]
There is no problem with the master branch parsing json, is it convenient to post your case?

**Comment by chovy-3012** [comment]
Here is my test code , this example is from official website.
```scala
    val spark = SparkSession.builder()
      .master("local")
      .getOrCreate()
    val df = spark.readStream
      .option("kafka.bootstrap.servers", kafkaServers)
      .option("startingOffsets", "latest")
      .option("subscribe", kafkaTopics)
      .format("kafka")
      .option("failOnDataLoss", false)
      .load()

    df.selectExpr("CAST(timestamp AS STRING)", "CAST(partition as STRING) as f2")
      .writeStream
      .format("doris")
      .option("checkpointLocation", "/tmp/test")
      .option("doris.table.identifier", dorisTable)
      .option("doris.fenodes", dorisFeNodes)
      .option("user", dorisUser)
      .option("password", dorisPwd)
      .option("doris.write.fields","f1,f2")
      .option("sink.batch.size",2)
      .option("sink.max-retries",2)
      .start().awaitTermination()
    spark.stop()
```

The above code runs with the following exception:
```
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('-' (code 45)): Expected space separating root-level values
 at [Source: (String)"2022-08-23 12:09:22.706"; line: 1, column: 6]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1840)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:712)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:637)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportMissingRootWS(ParserMinimalBase.java:684)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._verifyRootSpace(ReaderBasedJsonParser.java:1678)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._parsePosNumber(ReaderBasedJsonParser.java:1321)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:769)
	at com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4231)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2711)
	at org.apache.doris.spark.sql.DorisStreamLoadSink.$anonfun$write$3(DorisStreamLoadSink.scala:58)
	at org.apache.doris.spark.sql.DorisStreamLoadSink.$anonfun$write$3$adapted(DorisStreamLoadSink.scala:56)
	at scala.collection.immutable.Range.foreach(Range.scala:156)
	at org.apache.doris.spark.sql.DorisStreamLoadSink.$anonfun$write$2(DorisStreamLoadSink.scala:56)
	at org.apache.doris.spark.sql.DorisStreamLoadSink.$anonfun$write$2$adapted(DorisStreamLoadSink.scala:54)
	at scala.collection.Iterator.foreach(Iterator.scala:944)
	at scala.collection.Iterator.foreach$(Iterator.scala:944)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.foreach(WholeStageCodegenExec.scala:753)
	at org.apache.doris.spark.sql.DorisStreamLoadSink.$anonfun$write$1(DorisStreamLoadSink.scala:54)
	at org.apache.doris.spark.sql.DorisStreamLoadSink.$anonfun$write$1$adapted(DorisStreamLoadSink.scala:51)
	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2(RDD.scala:1020)
	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2$adapted(RDD.scala:1020)
	at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2236)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by caoliang-web** [comment]
Is it convenient for you to provide your kafka data?

**Review by caoliang-web — APPROVED** [review]
LGTM

**Comment by chovy-3012** [comment]
According to the code, I found that `dataframe` must convert to `json` for it to work.
Here is the code:
```scala
    df.selectExpr("CAST(timestamp AS STRING)", "CAST(partition as STRING) as f2")
      // must convert to json
      .toJSON
      .writeStream
      .format("doris")
      .option("checkpointLocation", "/tmp/test")
      .option("doris.table.identifier", dorisTable)
      .option("doris.fenodes", dorisFeNodes)
      .option("user", dorisUser)
      .option("password", dorisPwd)
      .option("doris.write.fields","f1,f2")
      .option("sink.batch.size",2)
      .option("sink.max-retries",2)
      .start().awaitTermination()
    spark.stop()
```

But `dataframe` should write to `doris` as expected.

**Review by hf200012 — APPROVED** [review]
LGTM

**Pull request merged**
