### PR TITLE
[improvement]Add an option to set the partition size of the final write stage

### PR DESCRIPTION
**Pull request by lexluo09**
# Proposed changes

Add an option to set the partition size of the final write stage

1. We can increase the parallelism of the computation and reduce the write doris parallelism to reduce write compaction pressure.
2. After the spark RDD is filtered, the number of records for each partition is small and the number of partitions is large. The writing frequency becomes high and resources are wasted.

## Problem Summary:

Describe the overview of changes.

## Checklist(Required)

1. Does it affect the original behavior: (Yes/No/I Don't know)
3. Has unit tests been added: (Yes/No/No Need)
4. Has document been added or modified: (Yes/No/No Need)
5. Does it need to update dependencies: (Yes/No)
6. Are there any changes that cannot be rolled back: (Yes/No)

## Further comments
before :
image

after :
image

image

### CODE REVIEW

**Comment by luolei604** [comment]
@hf200012  would you mind take a look?

**Comment by gnehil** [comment]
LGTM, and please update the docs on the official website to explain that `doris.sink.task.partition.size` is required, and the difference between setting `doris.sink.task.use.repartition` to true or false.

**Review by hf200012 — APPROVED** [review]
LGTM

**Comment by lexluo09** [comment]
> LGTM, and please update the docs on the official website to explain that `doris.sink.task.partition.size` is required, and the difference between setting `doris.sink.task.use.repartition` to true or false.

Ok, thank you very much for your advice

**Pull request merged**
